insert into departamento (depid, depnom) values(5,'Antioquia');
insert into departamento (depid, depnom) values(8,'Atlantico');
insert into departamento (depid, depnom) values(11,'Bogota D.C.');
insert into departamento (depid, depnom) values(13,'Bolivar');
insert into departamento (depid, depnom) values(15,'Boyaca');
insert into departamento (depid, depnom) values(17,'Caldas');
insert into departamento (depid, depnom) values(18,'Caqueta');
insert into departamento (depid, depnom) values(19,'Cauca');
insert into departamento (depid, depnom) values(20,'Cesar');
insert into departamento (depid, depnom) values(23,'Cordoba');
insert into departamento (depid, depnom) values(25,'Cundinamarca');
insert into departamento (depid, depnom) values(27,'Choco');
insert into departamento (depid, depnom) values(41,'Huila');
insert into departamento (depid, depnom) values(44,'La Guajira');
insert into departamento (depid, depnom) values(47,'Magdalena');
insert into departamento (depid, depnom) values(50,'Meta');
insert into departamento (depid, depnom) values(52,'Narino');
insert into departamento (depid, depnom) values(54,'Norte de Santander');
insert into departamento (depid, depnom) values(63,'Quindio');
insert into departamento (depid, depnom) values(66,'Risaralda');
insert into departamento (depid, depnom) values(68,'Santander');
insert into departamento (depid, depnom) values(70,'Sucre');
insert into departamento (depid, depnom) values(73,'Tolima');
insert into departamento (depid, depnom) values(76,'Valle del Cauca');
insert into departamento (depid, depnom) values(81,'Arauca');
insert into departamento (depid, depnom) values(85,'Casanare');
insert into departamento (depid, depnom) values(86,'Putumayo');
insert into departamento (depid, depnom) values(88,'San Andres');
insert into departamento (depid, depnom) values(91,'Amazonas');
insert into departamento (depid, depnom) values(94,'Guainia');
insert into departamento (depid, depnom) values(95,'Guaviare');
insert into departamento (depid, depnom) values(97,'Vaupes');
insert into departamento (depid, depnom) values(99,'Vichada');

insert into ciudad values(1, 'CUCUTA', 54);
insert into ciudad values(2, 'BOGOTA', 11);
insert into ciudad values(3, 'BOCHALEMA', 54);
insert into ciudad values(4, 'LOS PATIOS', 54);
insert into ciudad values(5, 'PAMPLONA', 54);
insert into ciudad values(6, 'PAMPLONITA', 54);
insert into ciudad values(7, 'VILLA DEL ROSARIO', 54);
insert into ciudad values(8, 'CHINACOTA', 54);
insert into ciudad values(9, 'CHITAGA', 54);
insert into ciudad values(10, 'MEDELLIN', 5);
insert into ciudad values(11, 'ENVIGADO', 5);
insert into ciudad values(12, 'ITAGUI', 5);
insert into ciudad values(13, 'RIO NEGRO', 5);
insert into ciudad values(14, 'ARAUCA', 81);
insert into ciudad values(15, 'BARRANQUILLA', 8);
insert into ciudad values(16, 'CARTAGENA', 13);
insert into ciudad values(17, 'MANIZALES', 17);
insert into ciudad values(18, 'POPAYAN', 19);
insert into ciudad values(19, 'VALLLEDUPAR', 20);
insert into ciudad values(20, 'BUCARAMANGA', 68);
insert into ciudad values(21, 'FLORIDA BLANCA', 68);
insert into ciudad values(22, 'PIEDECUESTA', 68);
insert into ciudad values(23, 'SAN GIL', 68);
insert into ciudad values(24, 'CALI', 76);
insert into ciudad values(25, 'TULUA', 76);
insert into ciudad values(26, 'ABEJORRAL', 5);
insert into ciudad values(27, 'ABREGO', 54);
insert into ciudad values(28, 'ABRIAQUI', 5);
insert into ciudad values(29, 'ACACIAS', 50);
insert into ciudad values(30, 'ACANDI', 27);
insert into ciudad values(31, 'ACEVEDO', 41);
insert into ciudad values(32, 'ACHI', 13);
insert into ciudad values(33, 'AGRADO', 41);
insert into ciudad values(34, 'AGUA DE DIOS', 25);
insert into ciudad values(35, 'AGUACHICA', 20);
insert into ciudad values(36, 'AGUADA', 68);
insert into ciudad values(37, 'AGUADAS', 17);
insert into ciudad values(38, 'AGUAZUL', 85);
insert into ciudad values(39, 'AGUSTIN CODAZZI', 20);
insert into ciudad values(40, 'AIPE', 41);
insert into ciudad values(41, 'ALBAN', 25);
insert into ciudad values(42, 'ALBAN', 52);
insert into ciudad values(43, 'ALBANIA', 18);
insert into ciudad values(44, 'ALBANIA', 44);
insert into ciudad values(45, 'ALBANIA', 68);
insert into ciudad values(46, 'ALCALA', 76);
insert into ciudad values(47, 'ALDANA', 52);
insert into ciudad values(48, 'ALEJANDRIA', 5);
insert into ciudad values(49, 'ALGARROBO', 47);
insert into ciudad values(50, 'ALGECIRAS', 41);
insert into ciudad values(51, 'ALMAGUER', 19);
insert into ciudad values(52, 'ALMEIDA', 15);
insert into ciudad values(53, 'ALPUJARRA', 73);
insert into ciudad values(54, 'ALTAMIRA', 41);
insert into ciudad values(55, 'ALTO BAUDO', 27);
insert into ciudad values(56, 'ALTOS DEL ROSARIO', 13);
insert into ciudad values(57, 'ALVARADO', 73);
insert into ciudad values(58, 'AMAGA', 5);
insert into ciudad values(59, 'AMALFI', 5);
insert into ciudad values(60, 'AMBALEMA', 73);
insert into ciudad values(61, 'ANAPOIMA', 25);
insert into ciudad values(62, 'ANCUYA', 52);
insert into ciudad values(63, 'ANDALUCIA', 76);
insert into ciudad values(64, 'ANDES', 5);
insert into ciudad values(65, 'ANGELOPOLIS', 5);
insert into ciudad values(66, 'ANGOSTURA', 5);
insert into ciudad values(67, 'ANOLAIMA', 25);
insert into ciudad values(68, 'ANORI', 5);
insert into ciudad values(69, 'ANSERMA', 17);
insert into ciudad values(70, 'ANSERMANUEVO', 76);
insert into ciudad values(71, 'ANTIOQUIA', 5);
insert into ciudad values(72, 'ANZA', 5);
insert into ciudad values(73, 'ANZOATEGUI', 73);
insert into ciudad values(74, 'APARTADO', 5);
insert into ciudad values(75, 'APIA', 66);
insert into ciudad values(76, 'APULO', 25);
insert into ciudad values(77, 'AQUITANIA', 15);
insert into ciudad values(78, 'ARACATACA', 47);
insert into ciudad values(79, 'ARANZAZU', 17);
insert into ciudad values(80, 'ARATOCA', 68);
insert into ciudad values(81, 'ARAUQUITA', 81);
insert into ciudad values(82, 'ARBELAEZ', 25);
insert into ciudad values(83, 'ARBOLEDA', 52);
insert into ciudad values(84, 'ARBOLEDAS', 54);
insert into ciudad values(85, 'ARBOLETES', 5);
insert into ciudad values(86, 'ARCABUCO', 15);
insert into ciudad values(87, 'ARENAL', 13);
insert into ciudad values(88, 'ARGELIA', 5);
insert into ciudad values(89, 'ARGELIA', 19);
insert into ciudad values(90, 'ARGELIA', 76);
insert into ciudad values(91, 'ARIGUANI', 47);
insert into ciudad values(92, 'ARJONA', 13);
insert into ciudad values(93, 'ARMENIA', 5);
insert into ciudad values(94, 'ARMENIA', 63);
insert into ciudad values(95, 'ARMERO', 73);
insert into ciudad values(96, 'ARROYOHONDO', 13);
insert into ciudad values(97, 'ASTREA', 20);
insert into ciudad values(98, 'ATACO', 73);
insert into ciudad values(99, 'ATRATO', 27);
insert into ciudad values(100, 'AYAPEL', 23);
insert into ciudad values(101, 'BAGADO', 27);
insert into ciudad values(102, 'BAHIA SOLANO', 27);
insert into ciudad values(103, 'BAJO BAUDO', 27);
insert into ciudad values(104, 'BALBOA', 19);
insert into ciudad values(105, 'BALBOA', 66);
insert into ciudad values(106, 'BARANOA', 8);
insert into ciudad values(107, 'BARAYA', 41);
insert into ciudad values(108, 'BARBACOAS', 52);
insert into ciudad values(109, 'BARBOSA', 5);
insert into ciudad values(110, 'BARBOSA', 68);
insert into ciudad values(111, 'BARICHARA', 68);
insert into ciudad values(112, 'BARRANCA DE UPIA', 50);
insert into ciudad values(113, 'BARRANCABERMEJA', 68);
insert into ciudad values(114, 'BARRANCAS', 44);
insert into ciudad values(115, 'BARRANCO DE LOBA', 13);
insert into ciudad values(116, 'BARRANCO MINAS', 94);
insert into ciudad values(117, 'BECERRIL', 20);
insert into ciudad values(118, 'BELALCAZAR', 17);
insert into ciudad values(119, 'BELEN', 15);
insert into ciudad values(120, 'BELEN', 52);
insert into ciudad values(121, 'BELEN DE BAJIRA', 27);
insert into ciudad values(122, 'BELEN DE LOS ANDAQUIES', 18);
insert into ciudad values(123, 'BELEN DE UMBRIA', 66);
insert into ciudad values(124, 'BELLO', 5);
insert into ciudad values(125, 'BELMIRA', 5);
insert into ciudad values(126, 'BELTRAN', 25);
insert into ciudad values(127, 'BERBEO', 15);
insert into ciudad values(128, 'BETANIA', 5);
insert into ciudad values(129, 'BETEITIVA', 15);
insert into ciudad values(130, 'BETULIA', 5);
insert into ciudad values(131, 'BETULIA', 68);
insert into ciudad values(132, 'BITUIMA', 25);
insert into ciudad values(133, 'BOAVITA', 15);
insert into ciudad values(134, 'BOJACA', 25);
insert into ciudad values(135, 'BOJAYA', 27);
insert into ciudad values(136, 'BOLIVAR', 19);
insert into ciudad values(137, 'BOLIVAR', 68);
insert into ciudad values(138, 'BOLIVAR', 76);
insert into ciudad values(139, 'BOSCONIA', 20);
insert into ciudad values(140, 'BOYACA', 15);
insert into ciudad values(141, 'BRICEï¿½O', 5);
insert into ciudad values(142, 'BRICEï¿½O', 15);
insert into ciudad values(143, 'BUCARASICA', 54);
insert into ciudad values(144, 'BUENAVENTURA', 76);
insert into ciudad values(145, 'BUENAVISTA', 15);
insert into ciudad values(146, 'BUENAVISTA', 23);
insert into ciudad values(147, 'BUENAVISTA', 63);
insert into ciudad values(148, 'BUENAVISTA', 70);
insert into ciudad values(149, 'BUENOS AIRES', 19);
insert into ciudad values(150, 'BUESACO', 52);
insert into ciudad values(151, 'BUGALAGRANDE', 76);
insert into ciudad values(152, 'BURITICA', 5);
insert into ciudad values(153, 'BUSBANZA', 15);
insert into ciudad values(154, 'CABRERA', 25);
insert into ciudad values(155, 'CABRERA', 68);
insert into ciudad values(156, 'CABUYARO', 50);
insert into ciudad values(157, 'CACAHUAL', 94);
insert into ciudad values(158, 'CACERES', 5);
insert into ciudad values(159, 'CACHIPAY', 25);
insert into ciudad values(160, 'CACHIRA', 54);
insert into ciudad values(161, 'CACOTA', 54);
insert into ciudad values(162, 'CAICEDO', 5);
insert into ciudad values(163, 'CAICEDONIA', 76);
insert into ciudad values(164, 'CAIMITO', 70);
insert into ciudad values(165, 'CAJAMARCA', 73);
insert into ciudad values(166, 'CAJIBIO', 19);
insert into ciudad values(167, 'CAJICA', 25);
insert into ciudad values(168, 'CALAMAR', 13);
insert into ciudad values(169, 'CALAMAR', 95);
insert into ciudad values(170, 'CALARCA', 63);
insert into ciudad values(171, 'CALDAS', 5);
insert into ciudad values(172, 'CALDAS', 15);
insert into ciudad values(173, 'CALDONO', 19);
insert into ciudad values(174, 'CALIFORNIA', 68);
insert into ciudad values(175, 'CALIMA', 76);
insert into ciudad values(176, 'CALOTO', 19);
insert into ciudad values(177, 'CAMPAMENTO', 5);
insert into ciudad values(178, 'CAMPO DE LA CRUZ', 8);
insert into ciudad values(179, 'CAMPOALEGRE', 41);
insert into ciudad values(180, 'CAMPOHERMOSO', 15);
insert into ciudad values(181, 'CANALETE', 23);
insert into ciudad values(182, 'CANDELARIA', 8);
insert into ciudad values(183, 'CANDELARIA', 76);
insert into ciudad values(184, 'CANTAGALLO', 13);
insert into ciudad values(185, 'CAï¿½ASGORDAS', 5);
insert into ciudad values(186, 'CAPARRAPI', 25);
insert into ciudad values(187, 'CAPITANEJO', 68);
insert into ciudad values(188, 'CAQUEZA', 25);
insert into ciudad values(189, 'CARACOLI', 5);
insert into ciudad values(190, 'CARAMANTA', 5);
insert into ciudad values(191, 'CARCASI', 68);
insert into ciudad values(192, 'CAREPA', 5);
insert into ciudad values(193, 'CARMEN DE APICALA', 73);
insert into ciudad values(194, 'CARMEN DE CARUPA', 25);
insert into ciudad values(195, 'CARMEN DEL DARIEN', 27);
insert into ciudad values(196, 'CAROLINA', 5);
insert into ciudad values(197, 'CARTAGENA DEL CHAIRA', 18);
insert into ciudad values(198, 'CARTAGO', 76);
insert into ciudad values(199, 'CARURU', 97);
insert into ciudad values(200, 'CASABIANCA', 73);
insert into ciudad values(201, 'CASTILLA LA NUEVA', 50);
insert into ciudad values(202, 'CAUCASIA', 5);
insert into ciudad values(203, 'CEPITA', 68);
insert into ciudad values(204, 'CERETE', 23);
insert into ciudad values(205, 'CERINZA', 15);
insert into ciudad values(206, 'CERRITO', 68);
insert into ciudad values(207, 'CERRO SAN ANTONIO', 47);
insert into ciudad values(208, 'CERTEGUI', 27);
insert into ciudad values(209, 'CHACHAGï¿½I', 52);
insert into ciudad values(210, 'CHAGUANI', 25);
insert into ciudad values(211, 'CHALAN', 70);
insert into ciudad values(212, 'CHAMEZA', 85);
insert into ciudad values(213, 'CHAPARRAL', 73);
insert into ciudad values(214, 'CHARALA', 68);
insert into ciudad values(215, 'CHARTA', 68);
insert into ciudad values(216, 'CHIA', 25);
insert into ciudad values(217, 'CHIGORODO', 5);
insert into ciudad values(218, 'CHIMA', 23);
insert into ciudad values(219, 'CHIMA', 68);
insert into ciudad values(220, 'CHIMICHAGUA', 20);
insert into ciudad values(221, 'CHINAVITA', 15);
insert into ciudad values(222, 'CHINCHINA', 17);
insert into ciudad values(223, 'CHINU', 23);
insert into ciudad values(224, 'CHIPAQUE', 25);
insert into ciudad values(225, 'CHIPATA', 68);
insert into ciudad values(226, 'CHIQUINQUIRA', 15);
insert into ciudad values(227, 'CHIQUIZA', 15);
insert into ciudad values(228, 'CHIRIGUANA', 20);
insert into ciudad values(229, 'CHISCAS', 15);
insert into ciudad values(230, 'CHITA', 15);
insert into ciudad values(231, 'CHITARAQUE', 15);
insert into ciudad values(232, 'CHIVATA', 15);
insert into ciudad values(233, 'CHIVOLO', 47);
insert into ciudad values(234, 'CHIVOR', 15);
insert into ciudad values(235, 'CHOACHI', 25);
insert into ciudad values(236, 'CHOCONTA', 25);
insert into ciudad values(237, 'CICUCO', 13);
insert into ciudad values(238, 'CIENAGA', 47);
insert into ciudad values(239, 'CIENAGA DE ORO', 23);
insert into ciudad values(240, 'CIENEGA', 15);
insert into ciudad values(241, 'CIMITARRA', 68);
insert into ciudad values(242, 'CIRCASIA', 63);
insert into ciudad values(243, 'CISNEROS', 5);
insert into ciudad values(244, 'CIUDAD BOLIVAR', 5);
insert into ciudad values(245, 'CLEMENCIA', 13);
insert into ciudad values(246, 'COCORNA', 5);
insert into ciudad values(247, 'COELLO', 73);
insert into ciudad values(248, 'COGUA', 25);
insert into ciudad values(249, 'COLOMBIA', 41);
insert into ciudad values(250, 'COLON', 52);
insert into ciudad values(251, 'COLON', 86);
insert into ciudad values(252, 'COLOSO', 70);
insert into ciudad values(253, 'COMBITA', 15);
insert into ciudad values(254, 'CONCEPCION', 5);
insert into ciudad values(255, 'CONCEPCION', 68);
insert into ciudad values(256, 'CONCORDIA', 5);
insert into ciudad values(257, 'CONCORDIA', 47);
insert into ciudad values(258, 'CONDOTO', 27);
insert into ciudad values(259, 'CONFINES', 68);
insert into ciudad values(260, 'CONSACA', 52);
insert into ciudad values(261, 'CONTADERO', 52);
insert into ciudad values(262, 'CONTRATACION', 68);
insert into ciudad values(263, 'CONVENCION', 54);
insert into ciudad values(264, 'COPACABANA', 5);
insert into ciudad values(265, 'COPER', 15);
insert into ciudad values(266, 'CORDOBA', 13);
insert into ciudad values(267, 'CORDOBA', 52);
insert into ciudad values(268, 'CORDOBA', 63);
insert into ciudad values(269, 'CORINTO', 19);
insert into ciudad values(270, 'COROMORO', 68);
insert into ciudad values(271, 'COROZAL', 70);
insert into ciudad values(272, 'CORRALES', 15);
insert into ciudad values(273, 'COTA', 25);
insert into ciudad values(274, 'COTORRA', 23);
insert into ciudad values(275, 'COVARACHIA', 15);
insert into ciudad values(276, 'COYAIMA', 73);
insert into ciudad values(277, 'CRAVO NORTE', 81);
insert into ciudad values(278, 'CUASPUD', 52);
insert into ciudad values(279, 'CUBARA', 15);
insert into ciudad values(280, 'CUBARRAL', 50);
insert into ciudad values(281, 'CUCAITA', 15);
insert into ciudad values(282, 'CUCUNUBA', 25);
insert into ciudad values(283, 'CUCUTILLA', 54);
insert into ciudad values(284, 'CUITIVA', 15);
insert into ciudad values(285, 'CUMARAL', 50);
insert into ciudad values(286, 'CUMARIBO', 99);
insert into ciudad values(287, 'CUMBAL', 52);
insert into ciudad values(288, 'CUMBITARA', 52);
insert into ciudad values(289, 'CUNDAY', 73);
insert into ciudad values(290, 'CURILLO', 18);
insert into ciudad values(291, 'CURITI', 68);
insert into ciudad values(292, 'CURUMANI', 20);
insert into ciudad values(293, 'DABEIBA', 5);
insert into ciudad values(294, 'DAGUA', 76);
insert into ciudad values(295, 'DIBULLA', 44);
insert into ciudad values(296, 'DISTRACCION', 44);
insert into ciudad values(297, 'DOLORES', 73);
insert into ciudad values(298, 'DON MATIAS', 5);
insert into ciudad values(299, 'DOSQUEBRADAS', 66);
insert into ciudad values(300, 'DUITAMA', 15);
insert into ciudad values(301, 'DURANIA', 54);
insert into ciudad values(302, 'EBEJICO', 5);
insert into ciudad values(303, 'EL AGUILA', 76);
insert into ciudad values(304, 'EL BAGRE', 5);
insert into ciudad values(305, 'EL BANCO', 47);
insert into ciudad values(306, 'EL CAIRO', 76);
insert into ciudad values(307, 'EL CALVARIO', 50);
insert into ciudad values(308, 'EL CANTON DEL SAN PABLO', 27);
insert into ciudad values(309, 'EL CARMEN', 54);
insert into ciudad values(310, 'EL CARMEN DE ATRATO', 27);
insert into ciudad values(311, 'EL CARMEN DE BOLIVAR', 13);
insert into ciudad values(312, 'EL CARMEN DE CHUCURI', 68);
insert into ciudad values(313, 'EL CARMEN DE VIBORAL', 5);
insert into ciudad values(314, 'EL CASTILLO', 50);
insert into ciudad values(315, 'EL CERRITO', 76);
insert into ciudad values(316, 'EL CHARCO', 52);
insert into ciudad values(317, 'EL COCUY', 15);
insert into ciudad values(318, 'EL COLEGIO', 25);
insert into ciudad values(319, 'EL COPEY', 20);
insert into ciudad values(320, 'EL DONCELLO', 18);
insert into ciudad values(321, 'EL DORADO', 50);
insert into ciudad values(322, 'EL DOVIO', 76);
insert into ciudad values(323, 'EL ENCANTO', 91);
insert into ciudad values(324, 'EL ESPINO', 15);
insert into ciudad values(325, 'EL GUACAMAYO', 68);
insert into ciudad values(326, 'EL GUAMO', 13);
insert into ciudad values(327, 'EL LITORAL DEL SAN JUAN', 27);
insert into ciudad values(328, 'EL MOLINO', 44);
insert into ciudad values(329, 'EL PASO', 20);
insert into ciudad values(330, 'EL PAUJIL', 18);
insert into ciudad values(331, 'EL PEï¿½OL', 52);
insert into ciudad values(332, 'EL PEï¿½ON', 13);
insert into ciudad values(333, 'EL PEï¿½ON', 25);
insert into ciudad values(334, 'EL PEï¿½ON', 68);
insert into ciudad values(335, 'EL PIï¿½ON', 47);
insert into ciudad values(336, 'EL PLAYON', 68);
insert into ciudad values(337, 'EL RETEN', 47);
insert into ciudad values(338, 'EL RETORNO', 95);
insert into ciudad values(339, 'EL ROBLE', 70);
insert into ciudad values(340, 'EL ROSAL', 25);
insert into ciudad values(341, 'EL ROSARIO', 52);
insert into ciudad values(342, 'EL SANTUARIO', 5);
insert into ciudad values(343, 'EL TABLON DE GOMEZ', 52);
insert into ciudad values(344, 'EL TAMBO', 19);
insert into ciudad values(345, 'EL TAMBO', 52);
insert into ciudad values(346, 'EL TARRA', 54);
insert into ciudad values(347, 'EL ZULIA', 54);
insert into ciudad values(348, 'ELIAS', 41);
insert into ciudad values(349, 'ENCINO', 68);
insert into ciudad values(350, 'ENCISO', 68);
insert into ciudad values(351, 'ENTRERRIOS', 5);
insert into ciudad values(352, 'ESPINAL', 73);
insert into ciudad values(353, 'FACATATIVA', 25);
insert into ciudad values(354, 'FALAN', 73);
insert into ciudad values(355, 'FILADELFIA', 17);
insert into ciudad values(356, 'FILANDIA', 63);
insert into ciudad values(357, 'FIRAVITOBA', 15);
insert into ciudad values(358, 'FLANDES', 73);
insert into ciudad values(359, 'FLORENCIA', 18);
insert into ciudad values(360, 'FLORENCIA', 19);
insert into ciudad values(361, 'FLORESTA', 15);
insert into ciudad values(362, 'FLORIAN', 68);
insert into ciudad values(363, 'FLORIDA', 76);
insert into ciudad values(364, 'FOMEQUE', 25);
insert into ciudad values(365, 'FONSECA', 44);
insert into ciudad values(366, 'FORTUL', 81);
insert into ciudad values(367, 'FOSCA', 25);
insert into ciudad values(368, 'FRANCISCO PIZARRO', 52);
insert into ciudad values(369, 'FREDONIA', 5);
insert into ciudad values(370, 'FRESNO', 73);
insert into ciudad values(371, 'FRONTINO', 5);
insert into ciudad values(372, 'FUENTE DE ORO', 50);
insert into ciudad values(373, 'FUNDACION', 47);
insert into ciudad values(374, 'FUNES', 52);
insert into ciudad values(375, 'FUNZA', 25);
insert into ciudad values(376, 'FUQUENE', 25);
insert into ciudad values(377, 'FUSAGASUGA', 25);
insert into ciudad values(378, 'GACHALA', 25);
insert into ciudad values(379, 'GACHANCIPA', 25);
insert into ciudad values(380, 'GACHANTIVA', 15);
insert into ciudad values(381, 'GACHETA', 25);
insert into ciudad values(382, 'GALAN', 68);
insert into ciudad values(383, 'GALAPA', 8);
insert into ciudad values(384, 'GALERAS', 70);
insert into ciudad values(385, 'GAMA', 25);
insert into ciudad values(386, 'GAMARRA', 20);
insert into ciudad values(387, 'GAMBITA', 68);
insert into ciudad values(388, 'GAMEZA', 15);
insert into ciudad values(389, 'GARAGOA', 15);
insert into ciudad values(390, 'GARZON', 41);
insert into ciudad values(391, 'GENOVA', 63);
insert into ciudad values(392, 'GIGANTE', 41);
insert into ciudad values(393, 'GINEBRA', 76);
insert into ciudad values(394, 'GIRALDO', 5);
insert into ciudad values(395, 'GIRARDOT', 25);
insert into ciudad values(396, 'GIRARDOTA', 5);
insert into ciudad values(397, 'GIRON', 68);
insert into ciudad values(398, 'GOMEZ PLATA', 5);
insert into ciudad values(399, 'GONZALEZ', 20);
insert into ciudad values(400, 'GRAMALOTE', 54);
insert into ciudad values(401, 'GRANADA', 5);
insert into ciudad values(402, 'GRANADA', 25);
insert into ciudad values(403, 'GRANADA', 50);
insert into ciudad values(404, 'GUACA', 68);
insert into ciudad values(405, 'GUACAMAYAS', 15);
insert into ciudad values(406, 'GUACARI', 76);
insert into ciudad values(407, 'GUACHETA', 25);
insert into ciudad values(408, 'GUACHUCAL', 52);
insert into ciudad values(409, 'GUADALAJARA DE BUGA', 76);
insert into ciudad values(410, 'GUADALUPE', 5);
insert into ciudad values(411, 'GUADALUPE', 41);
insert into ciudad values(412, 'GUADALUPE', 68);
insert into ciudad values(413, 'GUADUAS', 25);
insert into ciudad values(414, 'GUAITARILLA', 52);
insert into ciudad values(415, 'GUALMATAN', 52);
insert into ciudad values(416, 'GUAMAL', 47);
insert into ciudad values(417, 'GUAMAL', 50);
insert into ciudad values(418, 'GUAMO', 73);
insert into ciudad values(419, 'GUAPI', 19);
insert into ciudad values(420, 'GUAPOTA', 68);
insert into ciudad values(421, 'GUARANDA', 70);
insert into ciudad values(422, 'GUARNE', 5);
insert into ciudad values(423, 'GUASCA', 25);
insert into ciudad values(424, 'GUATAPE', 5);
insert into ciudad values(425, 'GUATAQUI', 25);
insert into ciudad values(426, 'GUATAVITA', 25);
insert into ciudad values(427, 'GUATEQUE', 15);
insert into ciudad values(428, 'GUATICA', 66);
insert into ciudad values(429, 'GUAVATA', 68);
insert into ciudad values(430, 'GUAYABAL DE SIQUIMA', 25);
insert into ciudad values(431, 'GUAYABETAL', 25);
insert into ciudad values(432, 'GUAYATA', 15);
insert into ciudad values(433, 'Gï¿½EPSA', 68);
insert into ciudad values(434, 'Gï¿½ICAN', 15);
insert into ciudad values(435, 'GUTIERREZ', 25);
insert into ciudad values(436, 'HACARI', 54);
insert into ciudad values(437, 'HATILLO DE LOBA', 13);
insert into ciudad values(438, 'HATO', 68);
insert into ciudad values(439, 'HATO COROZAL', 85);
insert into ciudad values(440, 'HATONUEVO', 44);
insert into ciudad values(441, 'HELICONIA', 5);
insert into ciudad values(442, 'HERRAN', 54);
insert into ciudad values(443, 'HERVEO', 73);
insert into ciudad values(444, 'HISPANIA', 5);
insert into ciudad values(445, 'HOBO', 41);
insert into ciudad values(446, 'HONDA', 73);
insert into ciudad values(447, 'IBAGUE', 73);
insert into ciudad values(448, 'ICONONZO', 73);
insert into ciudad values(449, 'ILES', 52);
insert into ciudad values(450, 'IMUES', 52);
insert into ciudad values(451, 'INIRIDA', 94);
insert into ciudad values(452, 'INZA', 19);
insert into ciudad values(453, 'IPIALES', 52);
insert into ciudad values(454, 'IQUIRA', 41);
insert into ciudad values(455, 'ISNOS', 41);
insert into ciudad values(456, 'ISTMINA', 27);
insert into ciudad values(457, 'ITUANGO', 5);
insert into ciudad values(458, 'IZA', 15);
insert into ciudad values(459, 'JAMBALO', 19);
insert into ciudad values(460, 'JAMUNDI', 76);
insert into ciudad values(461, 'JARDIN', 5);
insert into ciudad values(462, 'JENESANO', 15);
insert into ciudad values(463, 'JERICO', 5);
insert into ciudad values(464, 'JERICO', 15);
insert into ciudad values(465, 'JERUSALEN', 25);
insert into ciudad values(466, 'JESUS MARIA', 68);
insert into ciudad values(467, 'JORDAN', 68);
insert into ciudad values(468, 'JUAN DE ACOSTA', 8);
insert into ciudad values(469, 'JUNIN', 25);
insert into ciudad values(470, 'JURADO', 27);
insert into ciudad values(471, 'LA APARTADA', 23);
insert into ciudad values(472, 'LA ARGENTINA', 41);
insert into ciudad values(473, 'LA BELLEZA', 68);
insert into ciudad values(474, 'LA CALERA', 25);
insert into ciudad values(475, 'LA CAPILLA', 15);
insert into ciudad values(476, 'LA CEJA', 5);
insert into ciudad values(477, 'LA CELIA', 66);
insert into ciudad values(478, 'LA CHORRERA', 91);
insert into ciudad values(479, 'LA CRUZ', 52);
insert into ciudad values(480, 'LA CUMBRE', 76);
insert into ciudad values(481, 'LA DORADA', 17);
insert into ciudad values(482, 'LA ESPERANZA', 54);
insert into ciudad values(483, 'LA ESTRELLA', 5);
insert into ciudad values(484, 'LA FLORIDA', 52);
insert into ciudad values(485, 'LA GLORIA', 20);
insert into ciudad values(486, 'LA GUADALUPE', 94);
insert into ciudad values(487, 'LA JAGUA DE IBIRICO', 20);
insert into ciudad values(488, 'LA JAGUA DEL PILAR', 44);
insert into ciudad values(489, 'LA LLANADA', 52);
insert into ciudad values(490, 'LA MACARENA', 50);
insert into ciudad values(491, 'LA MERCED', 17);
insert into ciudad values(492, 'LA MESA', 25);
insert into ciudad values(493, 'LA MONTAï¿½ITA', 18);
insert into ciudad values(494, 'LA PALMA', 25);
insert into ciudad values(495, 'LA PAZ', 20);
insert into ciudad values(496, 'LA PAZ', 68);
insert into ciudad values(497, 'LA PEDRERA', 91);
insert into ciudad values(498, 'LA PEï¿½A', 25);
insert into ciudad values(499, 'LA PINTADA', 5);
insert into ciudad values(500, 'LA PLATA', 41);
insert into ciudad values(501, 'LA PLAYA', 54);
insert into ciudad values(502, 'LA PRIMAVERA', 99);
insert into ciudad values(503, 'LA SALINA', 85);
insert into ciudad values(504, 'LA SIERRA', 19);
insert into ciudad values(505, 'LA TEBAIDA', 63);
insert into ciudad values(506, 'LA TOLA', 52);
insert into ciudad values(507, 'LA UNION', 5);
insert into ciudad values(508, 'LA UNION', 52);
insert into ciudad values(509, 'LA UNION', 70);
insert into ciudad values(510, 'LA UNION', 76);
insert into ciudad values(511, 'LA UVITA', 15);
insert into ciudad values(512, 'LA VEGA', 19);
insert into ciudad values(513, 'LA VEGA', 25);
insert into ciudad values(514, 'LA VICTORIA', 91);
insert into ciudad values(515, 'LA VICTORIA', 15);
insert into ciudad values(516, 'LA VICTORIA', 76);
insert into ciudad values(517, 'LA VIRGINIA', 66);
insert into ciudad values(518, 'LABATECA', 54);
insert into ciudad values(519, 'LABRANZAGRANDE', 15);
insert into ciudad values(520, 'LANDAZURI', 68);
insert into ciudad values(521, 'LEBRIJA', 68);
insert into ciudad values(522, 'LEGUIZAMO', 86);
insert into ciudad values(523, 'LEIVA', 52);
insert into ciudad values(524, 'LEJANIAS', 50);
insert into ciudad values(525, 'LENGUAZAQUE', 25);
insert into ciudad values(526, 'LERIDA', 73);
insert into ciudad values(527, 'LETICIA', 91);
insert into ciudad values(528, 'LIBANO', 73);
insert into ciudad values(529, 'LIBORINA', 5);
insert into ciudad values(530, 'LINARES', 52);
insert into ciudad values(531, 'LLORO', 27);
insert into ciudad values(532, 'LOPEZ', 19);
insert into ciudad values(533, 'LORICA', 23);
insert into ciudad values(534, 'LOS ANDES', 52);
insert into ciudad values(535, 'LOS CORDOBAS', 23);
insert into ciudad values(536, 'LOS PALMITOS', 70);
insert into ciudad values(537, 'LOS SANTOS', 68);
insert into ciudad values(538, 'LOURDES', 54);
insert into ciudad values(539, 'LURUACO', 8);
insert into ciudad values(540, 'MACANAL', 15);
insert into ciudad values(541, 'MACARAVITA', 68);
insert into ciudad values(542, 'MACEO', 5);
insert into ciudad values(543, 'MACHETA', 25);
insert into ciudad values(544, 'MADRID', 25);
insert into ciudad values(545, 'MAGANGUE', 13);
insert into ciudad values(546, 'MAGï¿½I', 52);
insert into ciudad values(547, 'MAHATES', 13);
insert into ciudad values(548, 'MAICAO', 44);
insert into ciudad values(549, 'MAJAGUAL', 70);
insert into ciudad values(550, 'MALAGA', 68);
insert into ciudad values(551, 'MALAMBO', 8);
insert into ciudad values(552, 'MALLAMA', 52);
insert into ciudad values(553, 'MANATI', 8);
insert into ciudad values(554, 'MANAURE', 20);
insert into ciudad values(555, 'MANAURE', 44);
insert into ciudad values(556, 'MANI', 85);
insert into ciudad values(557, 'MANTA', 25);
insert into ciudad values(558, 'MANZANARES', 17);
insert into ciudad values(559, 'MAPIRIPAN', 50);
insert into ciudad values(560, 'MAPIRIPANA', 94);
insert into ciudad values(561, 'MARGARITA', 13);
insert into ciudad values(562, 'MARIA LA BAJA', 13);
insert into ciudad values(563, 'MARINILLA', 5);
insert into ciudad values(564, 'MARIPI', 15);
insert into ciudad values(565, 'MARIQUITA', 73);
insert into ciudad values(566, 'MARMATO', 17);
insert into ciudad values(567, 'MARQUETALIA', 17);
insert into ciudad values(568, 'MARSELLA', 66);
insert into ciudad values(569, 'MARULANDA', 17);
insert into ciudad values(570, 'MATANZA', 68);
insert into ciudad values(571, 'MEDINA', 25);
insert into ciudad values(572, 'MEDIO ATRATO', 27);
insert into ciudad values(573, 'MEDIO BAUDO', 27);
insert into ciudad values(574, 'MEDIO SAN JUAN', 27);
insert into ciudad values(575, 'MELGAR', 73);
insert into ciudad values(576, 'MERCADERES', 19);
insert into ciudad values(577, 'MESETAS', 50);
insert into ciudad values(578, 'MILAN', 18);
insert into ciudad values(579, 'MIRAFLORES', 15);
insert into ciudad values(580, 'MIRAFLORES', 95);
insert into ciudad values(581, 'MIRANDA', 19);
insert into ciudad values(582, 'MIRITI - PARANA', 91);
insert into ciudad values(583, 'MISTRATO', 66);
insert into ciudad values(584, 'MITU', 97);
insert into ciudad values(585, 'MOCOA', 86);
insert into ciudad values(586, 'MOGOTES', 68);
insert into ciudad values(587, 'MOLAGAVITA', 68);
insert into ciudad values(588, 'MOMIL', 23);
insert into ciudad values(589, 'MOMPOS', 13);
insert into ciudad values(590, 'MONGUA', 15);
insert into ciudad values(591, 'MONGUI', 15);
insert into ciudad values(592, 'MONIQUIRA', 15);
insert into ciudad values(593, 'MONTEBELLO', 5);
insert into ciudad values(594, 'MONTECRISTO', 13);
insert into ciudad values(595, 'MONTELIBANO', 23);
insert into ciudad values(596, 'MONTENEGRO', 63);
insert into ciudad values(597, 'MONTERIA', 23);
insert into ciudad values(598, 'MONTERREY', 85);
insert into ciudad values(599, 'MOï¿½ITOS', 23);
insert into ciudad values(600, 'MORALES', 13);
insert into ciudad values(601, 'MORALES', 19);
insert into ciudad values(602, 'MORELIA', 18);
insert into ciudad values(603, 'MORICHAL', 94);
insert into ciudad values(604, 'MORROA', 70);
insert into ciudad values(605, 'MOSQUERA', 25);
insert into ciudad values(606, 'MOSQUERA', 52);
insert into ciudad values(607, 'MOTAVITA', 15);
insert into ciudad values(608, 'MURILLO', 73);
insert into ciudad values(609, 'MURINDO', 5);
insert into ciudad values(610, 'MUTATA', 5);
insert into ciudad values(611, 'MUTISCUA', 54);
insert into ciudad values(612, 'MUZO', 15);
insert into ciudad values(613, 'NARIï¿½O', 25);
insert into ciudad values(614, 'NARIï¿½O', 52);
insert into ciudad values(615, 'NATAGA', 41);
insert into ciudad values(616, 'NATAGAIMA', 73);
insert into ciudad values(617, 'NECHI', 5);
insert into ciudad values(618, 'NECOCLI', 5);
insert into ciudad values(619, 'NEIRA', 17);
insert into ciudad values(620, 'NEIVA', 41);
insert into ciudad values(621, 'NEMOCON', 25);
insert into ciudad values(622, 'NILO', 25);
insert into ciudad values(623, 'NIMAIMA', 25);
insert into ciudad values(624, 'NOBSA', 15);
insert into ciudad values(625, 'NOCAIMA', 25);
insert into ciudad values(626, 'NORCASIA', 17);
insert into ciudad values(627, 'NOVITA', 27);
insert into ciudad values(628, 'NUEVA GRANADA', 47);
insert into ciudad values(629, 'NUEVO COLON', 15);
insert into ciudad values(630, 'NUNCHIA', 85);
insert into ciudad values(631, 'NUQUI', 27);
insert into ciudad values(632, 'OBANDO', 76);
insert into ciudad values(633, 'OCAMONTE', 68);
insert into ciudad values(634, 'OCAï¿½A', 54);
insert into ciudad values(635, 'OIBA', 68);
insert into ciudad values(636, 'OICATA', 15);
insert into ciudad values(637, 'OLAYA', 5);
insert into ciudad values(638, 'OLAYA HERRERA', 52);
insert into ciudad values(639, 'ONZAGA', 68);
insert into ciudad values(640, 'OPORAPA', 41);
insert into ciudad values(641, 'ORITO', 86);
insert into ciudad values(642, 'OROCUE', 85);
insert into ciudad values(643, 'ORTEGA', 73);
insert into ciudad values(644, 'OSPINA', 52);
insert into ciudad values(645, 'OTANCHE', 15);
insert into ciudad values(646, 'OVEJAS', 70);
insert into ciudad values(647, 'PACHAVITA', 15);
insert into ciudad values(648, 'PACHO', 25);
insert into ciudad values(649, 'PACOA', 97);
insert into ciudad values(650, 'PACORA', 17);
insert into ciudad values(651, 'PADILLA', 19);
insert into ciudad values(652, 'PAEZ', 15);
insert into ciudad values(653, 'PAEZ', 19);
insert into ciudad values(654, 'PAICOL', 41);
insert into ciudad values(655, 'PAILITAS', 20);
insert into ciudad values(656, 'PAIME', 25);
insert into ciudad values(657, 'PAIPA', 15);
insert into ciudad values(658, 'PAJARITO', 15);
insert into ciudad values(659, 'PALERMO', 41);
insert into ciudad values(660, 'PALESTINA', 17);
insert into ciudad values(661, 'PALESTINA', 41);
insert into ciudad values(662, 'PALMAR', 68);
insert into ciudad values(663, 'PALMAR DE VARELA', 8);
insert into ciudad values(664, 'PALMAS DEL SOCORRO', 68);
insert into ciudad values(665, 'PALMIRA', 76);
insert into ciudad values(666, 'PALMITO', 70);
insert into ciudad values(667, 'PALOCABILDO', 73);
insert into ciudad values(668, 'PANA PANA', 94);
insert into ciudad values(669, 'PANDI', 25);
insert into ciudad values(670, 'PANQUEBA', 15);
insert into ciudad values(671, 'PAPUNAUA', 97);
insert into ciudad values(672, 'PARAMO', 68);
insert into ciudad values(673, 'PARATEBUENO', 25);
insert into ciudad values(674, 'PASCA', 25);
insert into ciudad values(675, 'PASTO', 52);
insert into ciudad values(676, 'PATIA', 19);
insert into ciudad values(677, 'PAUNA', 15);
insert into ciudad values(678, 'PAYA', 15);
insert into ciudad values(679, 'PAZ DE ARIPORO', 85);
insert into ciudad values(680, 'PAZ DE RIO', 15);
insert into ciudad values(681, 'PEDRAZA', 47);
insert into ciudad values(682, 'PELAYA', 20);
insert into ciudad values(683, 'PENSILVANIA', 17);
insert into ciudad values(684, 'PENOL', 5);
insert into ciudad values(685, 'PEQUE', 5);
insert into ciudad values(686, 'PEREIRA', 66);
insert into ciudad values(687, 'PESCA', 15);
insert into ciudad values(688, 'PIAMONTE', 19);
insert into ciudad values(689, 'PIEDRAS', 73);
insert into ciudad values(690, 'PIENDAMO', 19);
insert into ciudad values(691, 'PIJAO', 63);
insert into ciudad values(692, 'PIJINO DEL CARMEN', 47);
insert into ciudad values(693, 'PINCHOTE', 68);
insert into ciudad values(694, 'PINILLOS', 13);
insert into ciudad values(695, 'PIOJO', 8);
insert into ciudad values(696, 'PISBA', 15);
insert into ciudad values(697, 'PITAL', 41);
insert into ciudad values(698, 'PITALITO', 41);
insert into ciudad values(699, 'PIVIJAY', 47);
insert into ciudad values(700, 'PLANADAS', 73);
insert into ciudad values(701, 'PLANETA RICA', 23);
insert into ciudad values(702, 'PLATO', 47);
insert into ciudad values(703, 'POLICARPA', 52);
insert into ciudad values(704, 'POLONUEVO', 8);
insert into ciudad values(705, 'PONEDERA', 8);
insert into ciudad values(706, 'PORE', 85);
insert into ciudad values(707, 'POTOSI', 52);
insert into ciudad values(708, 'PRADERA', 76);
insert into ciudad values(709, 'PRADO', 73);
insert into ciudad values(710, 'PROVIDENCIA', 88);
insert into ciudad values(711, 'PROVIDENCIA', 52);
insert into ciudad values(712, 'PUEBLO BELLO', 20);
insert into ciudad values(713, 'PUEBLO NUEVO', 23);
insert into ciudad values(714, 'PUEBLO RICO', 66);
insert into ciudad values(715, 'PUEBLORRICO', 5);
insert into ciudad values(716, 'PUEBLOVIEJO', 47);
insert into ciudad values(717, 'PUENTE NACIONAL', 68);
insert into ciudad values(718, 'PUERRES', 52);
insert into ciudad values(719, 'PUERTO', 68);
insert into ciudad values(720, 'PUERTO ALEGRIA', 91);
insert into ciudad values(721, 'PUERTO ARICA', 91);
insert into ciudad values(722, 'PUERTO ASIS', 86);
insert into ciudad values(723, 'PUERTO BERRIO', 5);
insert into ciudad values(724, 'PUERTO BOYACA', 15);
insert into ciudad values(725, 'PUERTO CAICEDO', 86);
insert into ciudad values(726, 'PUERTO CARRENO', 99);
insert into ciudad values(727, 'PUERTO COLOMBIA', 8);
insert into ciudad values(728, 'PUERTO COLOMBIA', 94);
insert into ciudad values(729, 'PUERTO CONCORDIA', 50);
insert into ciudad values(730, 'PUERTO ESCONDIDO', 23);
insert into ciudad values(731, 'PUERTO GAITAN', 50);
insert into ciudad values(732, 'PUERTO GUZMAN', 86);
insert into ciudad values(733, 'PUERTO LIBERTADOR', 23);
insert into ciudad values(734, 'PUERTO LLERAS', 50);
insert into ciudad values(735, 'PUERTO LOPEZ', 50);
insert into ciudad values(736, 'PUERTO NARE', 5);
insert into ciudad values(737, 'PUERTO NARINO', 91);
insert into ciudad values(738, 'PUERTO PARRA', 68);
insert into ciudad values(739, 'PUERTO RICO', 18);
insert into ciudad values(740, 'PUERTO RICO', 50);
insert into ciudad values(741, 'PUERTO RONDON', 81);
insert into ciudad values(742, 'PUERTO SALGAR', 25);
insert into ciudad values(743, 'PUERTO Santander', 91);
insert into ciudad values(744, 'PUERTO TEJADA', 19);
insert into ciudad values(745, 'PUERTO TRIUNFO', 5);
insert into ciudad values(746, 'PUERTO WILCHES', 68);
insert into ciudad values(747, 'PULI', 25);
insert into ciudad values(748, 'PUPIALES', 52);
insert into ciudad values(749, 'PURACE', 19);
insert into ciudad values(750, 'PURIFICACION', 73);
insert into ciudad values(751, 'PURISIMA', 23);
insert into ciudad values(752, 'QUEBRADANEGRA', 25);
insert into ciudad values(753, 'QUETAME', 25);
insert into ciudad values(754, 'QUIBDO', 27);
insert into ciudad values(755, 'QUIMBAYA', 63);
insert into ciudad values(756, 'QUINCHIA', 66);
insert into ciudad values(757, 'QUIPAMA', 15);
insert into ciudad values(758, 'QUIPILE', 25);
insert into ciudad values(759, 'RAGONVALIA', 54);
insert into ciudad values(760, 'RAMIRIQUI', 15);
insert into ciudad values(761, 'RAQUIRA', 15);
insert into ciudad values(762, 'RECETOR', 85);
insert into ciudad values(763, 'REGIDOR', 13);
insert into ciudad values(764, 'REMEDIOS', 5);
insert into ciudad values(765, 'REMOLINO', 47);
insert into ciudad values(766, 'REPELON', 8);
insert into ciudad values(767, 'RESTREPO', 50);
insert into ciudad values(768, 'RESTREPO', 76);
insert into ciudad values(769, 'RETIRO', 5);
insert into ciudad values(770, 'RICAURTE', 25);
insert into ciudad values(771, 'RICAURTE', 52);
insert into ciudad values(772, 'RIO DE ORO', 20);
insert into ciudad values(773, 'RIO IRO', 27);
insert into ciudad values(774, 'RIO QUITO', 27);
insert into ciudad values(775, 'RIO VIEJO', 13);
insert into ciudad values(776, 'RIOBLANCO', 73);
insert into ciudad values(777, 'RIOFRIO', 76);
insert into ciudad values(778, 'RIOHACHA', 44);
insert into ciudad values(779, 'RIONEGRO', 68);
insert into ciudad values(780, 'RIOSUCIO', 17);
insert into ciudad values(781, 'RIOSUCIO', 27);
insert into ciudad values(782, 'RISARALDA', 17);
insert into ciudad values(783, 'RIVERA', 41);
insert into ciudad values(784, 'ROBERTO PAYAN', 52);
insert into ciudad values(785, 'ROLDANILLO', 76);
insert into ciudad values(786, 'RONCESVALLES', 73);
insert into ciudad values(787, 'RONDON', 15);
insert into ciudad values(788, 'ROSAS', 19);
insert into ciudad values(789, 'ROVIRA', 73);
insert into ciudad values(790, 'SABANA DE TORRES', 68);
insert into ciudad values(791, 'SABANAGRANDE', 8);
insert into ciudad values(792, 'SABANALARGA', 5);
insert into ciudad values(793, 'SABANALARGA', 8);
insert into ciudad values(794, 'SABANALARGA', 85);
insert into ciudad values(795, 'SABANAS DE SAN ANGEL', 47);
insert into ciudad values(796, 'SABANETA', 5);
insert into ciudad values(797, 'SABOYA', 15);
insert into ciudad values(798, 'SACAMA', 85);
insert into ciudad values(799, 'SACHICA', 15);
insert into ciudad values(800, 'SAHAGUN', 23);
insert into ciudad values(801, 'SALADOBLANCO', 41);
insert into ciudad values(802, 'SALAMINA', 17);
insert into ciudad values(803, 'SALAMINA', 47);
insert into ciudad values(804, 'SALAZAR', 54);
insert into ciudad values(805, 'SALDANA', 73);
insert into ciudad values(806, 'SALENTO', 63);
insert into ciudad values(807, 'SALGAR', 5);
insert into ciudad values(808, 'SAMACA', 15);
insert into ciudad values(809, 'SAMANA', 17);
insert into ciudad values(810, 'SAMANIEGO', 52);
insert into ciudad values(811, 'SAMPUES', 70);
insert into ciudad values(812, 'SAN AGUSTIN', 41);
insert into ciudad values(813, 'SAN ALBERTO', 20);
insert into ciudad values(814, 'SAN ANDRES', 5);
insert into ciudad values(815, 'SAN ANDRES', 88);
insert into ciudad values(816, 'SAN ANDRES', 68);
insert into ciudad values(817, 'SAN ANDRES DE SOTAVENTO', 23);
insert into ciudad values(818, 'SAN ANTERO', 23);
insert into ciudad values(819, 'SAN ANTONIO', 73);
insert into ciudad values(820, 'SAN ANTONIO DEL TEQUENDAMA', 25);
insert into ciudad values(821, 'SAN BENITO', 68);
insert into ciudad values(822, 'SAN BENITO ABAD', 70);
insert into ciudad values(823, 'SAN BERNARDO', 25);
insert into ciudad values(824, 'SAN BERNARDO', 52);
insert into ciudad values(825, 'SAN BERNARDO DEL VIENTO', 23);
insert into ciudad values(826, 'SAN CALIXTO', 54);
insert into ciudad values(827, 'SAN CARLOS', 5);
insert into ciudad values(828, 'SAN CARLOS', 23);
insert into ciudad values(829, 'SAN CARLOS DE GUAROA', 50);
insert into ciudad values(830, 'SAN CAYETANO', 25);
insert into ciudad values(831, 'SAN CAYETANO', 54);
insert into ciudad values(832, 'SAN CRISTOBAL', 13);
insert into ciudad values(833, 'SAN DIEGO', 20);
insert into ciudad values(834, 'SAN EDUARDO', 15);
insert into ciudad values(835, 'SAN ESTANISLAO', 13);
insert into ciudad values(836, 'SAN FELIPE', 94);
insert into ciudad values(837, 'SAN FERNANDO', 13);
insert into ciudad values(838, 'SAN FRANCISCO', 5);
insert into ciudad values(839, 'SAN FRANCISCO', 25);
insert into ciudad values(840, 'SAN FRANCISCO', 86);
insert into ciudad values(841, 'SAN JACINTO', 13);
insert into ciudad values(842, 'SAN JACINTO DEL', 19);
insert into ciudad values(843, 'SAN JERONIMO', 5);
insert into ciudad values(844, 'SAN JOAQUIN', 68);
insert into ciudad values(845, 'SAN JOSE', 17);
insert into ciudad values(846, 'SAN JOSE DE LA FRAGUA', 18);
insert into ciudad values(847, 'SAN JOSE DE LA MONTAnA', 5);
insert into ciudad values(848, 'SAN JOSE DE MIRANDA', 68);
insert into ciudad values(849, 'SAN JOSE DE PARE', 15);
insert into ciudad values(850, 'SAN JOSE DEL Guaviare', 95);
insert into ciudad values(851, 'SAN JOSE DEL PALMAR', 27);
insert into ciudad values(852, 'SAN JUAN DE ARAMA', 50);
insert into ciudad values(853, 'SAN JUAN DE BETULIA', 70);
insert into ciudad values(854, 'SAN JUAN DE RIO SECO', 25);
insert into ciudad values(855, 'SAN JUAN DE URABA', 5);
insert into ciudad values(856, 'SAN JUAN DEL', 20);
insert into ciudad values(857, 'SAN JUAN NEPOMUCENO', 13);
insert into ciudad values(858, 'SAN JUANITO', 50);
insert into ciudad values(859, 'SAN LORENZO', 52);
insert into ciudad values(860, 'SAN LUIS', 5);
insert into ciudad values(861, 'SAN LUIS', 73);
insert into ciudad values(862, 'SAN LUIS DE GACENO', 15);
insert into ciudad values(863, 'SAN LUIS DE PALENQUE', 85);
insert into ciudad values(864, 'SAN MARCOS', 70);
insert into ciudad values(865, 'SAN MARTIN', 20);
insert into ciudad values(866, 'SAN MARTIN', 50);
insert into ciudad values(867, 'SAN MARTIN DE LOBA', 13);
insert into ciudad values(868, 'SAN MATEO', 15);
insert into ciudad values(869, 'SAN MIGUEL', 86);
insert into ciudad values(870, 'SAN MIGUEL', 68);
insert into ciudad values(871, 'SAN MIGUEL DE SEMA', 15);
insert into ciudad values(872, 'SAN ONOFRE', 70);
insert into ciudad values(873, 'SAN PABLO', 13);
insert into ciudad values(874, 'SAN PABLO', 52);
insert into ciudad values(875, 'SAN PABLO DE BORBUR', 15);
insert into ciudad values(876, 'SAN PEDRO', 5);
insert into ciudad values(877, 'SAN PEDRO', 70);
insert into ciudad values(878, 'SAN PEDRO', 76);
insert into ciudad values(879, 'SAN PEDRO DE CARTAGO', 52);
insert into ciudad values(880, 'SAN PEDRO DE URABA', 5);
insert into ciudad values(881, 'SAN PELAYO', 23);
insert into ciudad values(882, 'SAN RAFAEL', 5);
insert into ciudad values(883, 'SAN ROQUE', 5);
insert into ciudad values(884, 'SAN SEBASTIAN', 19);
insert into ciudad values(885, 'SAN SEBASTIAN DE BUENAVISTA', 47);
insert into ciudad values(886, 'SAN VICENTE', 5);
insert into ciudad values(887, 'SAN VICENTE DE CHUCURI', 68);
insert into ciudad values(888, 'SAN VICENTE DEL CAGUAN', 18);
insert into ciudad values(889, 'SAN ZENON', 47);
insert into ciudad values(890, 'SANDONA', 52);
insert into ciudad values(891, 'SANTA ANA', 47);
insert into ciudad values(892, 'SANTA BARBARA', 5);
insert into ciudad values(893, 'SANTA BARBARA', 52);
insert into ciudad values(894, 'SANTA BARBARA', 68);
insert into ciudad values(895, 'SANTA BARBARA DE PINTO', 47);
insert into ciudad values(896, 'SANTA CATALINA', 13);
insert into ciudad values(897, 'SANTA HELENA DEL OPON', 68);
insert into ciudad values(898, 'SANTA ISABEL', 73);
insert into ciudad values(899, 'SANTA LUCIA', 8);
insert into ciudad values(900, 'SANTA MARIA', 15);
insert into ciudad values(901, 'SANTA MARIA', 41);
insert into ciudad values(902, 'SANTA MARTA', 47);
insert into ciudad values(903, 'SANTA ROSA', 13);
insert into ciudad values(904, 'SANTA ROSA', 19);
insert into ciudad values(905, 'SANTA ROSA DE CABAL', 66);
insert into ciudad values(906, 'SANTA ROSA DE OSOS', 5);
insert into ciudad values(907, 'SANTA ROSA DE VITERBO', 15);
insert into ciudad values(908, 'SANTA ROSA DEL SUR', 13);
insert into ciudad values(909, 'SANTA ROSALIA', 99);
insert into ciudad values(910, 'SANTA SOFIA', 15);
insert into ciudad values(911, 'SANTACRUZ', 52);
insert into ciudad values(912, 'SANTAFE DE', 5);
insert into ciudad values(913, 'SANTANA', 15);
insert into ciudad values(914, 'SANTANDER DE QUILICHAO', 19);
insert into ciudad values(915, 'SANTIAGO', 54);
insert into ciudad values(916, 'SANTIAGO', 86);
insert into ciudad values(917, 'SANTIAGO DE TOLU', 70);
insert into ciudad values(918, 'SANTO DOMINGO', 5);
insert into ciudad values(919, 'SANTO TOMAS', 8);
insert into ciudad values(920, 'SANTUARIO', 66);
insert into ciudad values(921, 'SAPUYES', 52);
insert into ciudad values(922, 'SARAVENA', 81);
insert into ciudad values(923, 'SARDINATA', 54);
insert into ciudad values(924, 'SASAIMA', 25);
insert into ciudad values(925, 'SATIVANORTE', 15);
insert into ciudad values(926, 'SATIVASUR', 15);
insert into ciudad values(927, 'SEGOVIA', 5);
insert into ciudad values(928, 'SESQUILE', 25);
insert into ciudad values(929, 'SEVILLA', 76);
insert into ciudad values(930, 'SIACHOQUE', 15);
insert into ciudad values(931, 'SIBATE', 25);
insert into ciudad values(932, 'SIBUNDOY', 86);
insert into ciudad values(933, 'SILOS', 54);
insert into ciudad values(934, 'SILVANIA', 25);
insert into ciudad values(935, 'SILVIA', 19);
insert into ciudad values(936, 'SIMACOTA', 68);
insert into ciudad values(937, 'SIMIJACA', 25);
insert into ciudad values(938, 'SIMITI', 13);
insert into ciudad values(939, 'SINCE', 70);
insert into ciudad values(940, 'SINCELEJO', 70);
insert into ciudad values(941, 'SIPI', 27);
insert into ciudad values(942, 'SITIONUEVO', 47);
insert into ciudad values(943, 'SOACHA', 25);
insert into ciudad values(944, 'SOATA', 15);
insert into ciudad values(945, 'SOCHA', 15);
insert into ciudad values(946, 'SOCORRO', 68);
insert into ciudad values(947, 'SOCOTA', 15);
insert into ciudad values(948, 'SOGAMOSO', 15);
insert into ciudad values(949, 'SOLANO', 18);
insert into ciudad values(950, 'SOLEDAD', 8);
insert into ciudad values(951, 'SOLITA', 18);
insert into ciudad values(952, 'SOMONDOCO', 15);
insert into ciudad values(953, 'SONSON', 5);
insert into ciudad values(954, 'SOPETRAN', 5);
insert into ciudad values(955, 'SOPLAVIENTO', 13);
insert into ciudad values(956, 'SOPO', 25);
insert into ciudad values(957, 'SORA', 15);
insert into ciudad values(958, 'SORACA', 15);
insert into ciudad values(959, 'SOTAQUIRA', 15);
insert into ciudad values(960, 'SOTARA', 19);
insert into ciudad values(961, 'SUAITA', 68);
insert into ciudad values(962, 'SUAN', 8);
insert into ciudad values(963, 'SUAREZ', 19);
insert into ciudad values(964, 'SUAREZ', 73);
insert into ciudad values(965, 'SUAZA', 41);
insert into ciudad values(966, 'SUBACHOQUE', 25);
insert into ciudad values(967, 'SUCRE', 68);
insert into ciudad values(968, 'SUCRE', 70);
insert into ciudad values(969, 'SUESCA', 25);
insert into ciudad values(970, 'SUPATA', 25);
insert into ciudad values(971, 'SUPIA', 17);
insert into ciudad values(972, 'SURATA', 68);
insert into ciudad values(973, 'SUSA', 25);
insert into ciudad values(974, 'SUSACON', 15);
insert into ciudad values(975, 'SUTAMARCHAN', 15);
insert into ciudad values(976, 'SUTATAUSA', 25);
insert into ciudad values(977, 'SUTATENZA', 15);
insert into ciudad values(978, 'TABIO', 25);
insert into ciudad values(979, 'TADO', 27);
insert into ciudad values(980, 'TALAIGUA NUEVO', 13);
insert into ciudad values(981, 'TAMALAMEQUE', 20);
insert into ciudad values(982, 'TAMARA', 85);
insert into ciudad values(983, 'TAME', 81);
insert into ciudad values(984, 'TAMESIS', 5);
insert into ciudad values(985, 'TAMINANGO', 52);
insert into ciudad values(986, 'TANGUA', 52);
insert into ciudad values(987, 'TARAIRA', 97);
insert into ciudad values(988, 'TARAPACA', 91);
insert into ciudad values(989, 'TARAZA', 5);
insert into ciudad values(990, 'TARQUI', 41);
insert into ciudad values(991, 'TARSO', 5);
insert into ciudad values(992, 'TASCO', 15);
insert into ciudad values(993, 'TAURAMENA', 85);
insert into ciudad values(994, 'TAUSA', 25);
insert into ciudad values(995, 'TELLO', 41);
insert into ciudad values(996, 'TENA', 25);
insert into ciudad values(997, 'TENERIFE', 47);
insert into ciudad values(998, 'TENJO', 25);
insert into ciudad values(999, 'TENZA', 15);
insert into ciudad values(1000, 'TEORAMA', 54);
insert into ciudad values(1001, 'TERUEL', 41);
insert into ciudad values(1002, 'TESALIA', 41);
insert into ciudad values(1003, 'TIBACUY', 25);
insert into ciudad values(1004, 'TIBANA', 15);
insert into ciudad values(1005, 'TIBASOSA', 15);
insert into ciudad values(1006, 'TIBIRITA', 25);
insert into ciudad values(1007, 'TIBU', 54);
insert into ciudad values(1008, 'TIERRALTA', 23);
insert into ciudad values(1009, 'TIMANA', 41);
insert into ciudad values(1010, 'TIMBIO', 19);
insert into ciudad values(1011, 'TIMBIQUI', 19);
insert into ciudad values(1012, 'TINJACA', 15);
insert into ciudad values(1013, 'TIPACOQUE', 15);
insert into ciudad values(1014, 'TIQUISIO', 13);
insert into ciudad values(1015, 'TITIRIBI', 5);
insert into ciudad values(1016, 'TOCA', 15);
insert into ciudad values(1017, 'TOCAIMA', 25);
insert into ciudad values(1018, 'TOCANCIPA', 25);
insert into ciudad values(1019, 'TOGï¿½I', 15);
insert into ciudad values(1020, 'TOLEDO', 5);
insert into ciudad values(1021, 'TOLEDO', 54);
insert into ciudad values(1022, 'TOLUVIEJO', 70);
insert into ciudad values(1023, 'TONA', 68);
insert into ciudad values(1024, 'TOPAGA', 15);
insert into ciudad values(1025, 'TOPAIPI', 25);
insert into ciudad values(1026, 'TORIBIO', 19);
insert into ciudad values(1027, 'TORO', 76);
insert into ciudad values(1028, 'TOTA', 15);
insert into ciudad values(1029, 'TOTORO', 19);
insert into ciudad values(1030, 'TRINIDAD', 85);
insert into ciudad values(1031, 'TRUJILLO', 76);
insert into ciudad values(1032, 'TUBARA', 8);
insert into ciudad values(1033, 'TUMACO', 52);
insert into ciudad values(1034, 'TUNJA', 15);
insert into ciudad values(1035, 'TUNUNGUA', 15);
insert into ciudad values(1036, 'TUQUERRES', 52);
insert into ciudad values(1037, 'TURBACO', 13);
insert into ciudad values(1038, 'TURBANA', 13);
insert into ciudad values(1039, 'TURBO', 5);
insert into ciudad values(1040, 'TURMEQUE', 15);
insert into ciudad values(1041, 'TUTA', 15);
insert into ciudad values(1042, 'TUTAZA', 15);
insert into ciudad values(1043, 'UBALA', 25);
insert into ciudad values(1044, 'UBAQUE', 25);
insert into ciudad values(1045, 'ULLOA', 76);
insert into ciudad values(1046, 'UMBITA', 15);
insert into ciudad values(1047, 'UNE', 25);
insert into ciudad values(1048, 'UNGUIA', 27);
insert into ciudad values(1049, 'UNION PANAMERICANA', 27);
insert into ciudad values(1050, 'URAMITA', 5);
insert into ciudad values(1051, 'URIBE', 50);
insert into ciudad values(1052, 'URIBIA', 44);
insert into ciudad values(1053, 'URRAO', 5);
insert into ciudad values(1054, 'URUMITA', 44);
insert into ciudad values(1055, 'USIACURI', 8);
insert into ciudad values(1056, 'UTICA', 25);
insert into ciudad values(1057, 'VALDIVIA', 5);
insert into ciudad values(1058, 'VALENCIA', 23);
insert into ciudad values(1059, 'VALLE DE SAN JOSE', 68);
insert into ciudad values(1060, 'VALLE DE SAN JUAN', 73);
insert into ciudad values(1061, 'VALLE DEL GUAMUEZ', 86);
insert into ciudad values(1062, 'VALPARAISO', 5);
insert into ciudad values(1063, 'VALPARAISO', 18);
insert into ciudad values(1064, 'VEGACHI', 5);
insert into ciudad values(1065, 'VELEZ', 68);
insert into ciudad values(1066, 'VENADILLO', 73);
insert into ciudad values(1067, 'VENECIA', 5);
insert into ciudad values(1068, 'VENECIA', 25);
insert into ciudad values(1069, 'VENTAQUEMADA', 15);
insert into ciudad values(1070, 'VERGARA', 25);
insert into ciudad values(1071, 'VERSALLES', 76);
insert into ciudad values(1072, 'VETAS', 68);
insert into ciudad values(1073, 'VIANI', 25);
insert into ciudad values(1074, 'VICTORIA', 17);
insert into ciudad values(1075, 'VIGIA DEL FUERTE', 5);
insert into ciudad values(1076, 'VIJES', 76);
insert into ciudad values(1077, 'VILLA CARO', 54);
insert into ciudad values(1078, 'VILLA DE LEYVA', 15);
insert into ciudad values(1079, 'VILLA DE SAN DIEGO DE UBATE', 25);
insert into ciudad values(1080, 'VILLA RICA', 19);
insert into ciudad values(1081, 'VILLAGARZON', 86);
insert into ciudad values(1082, 'VILLAGOMEZ', 25);
insert into ciudad values(1083, 'VILLAHERMOSA', 73);
insert into ciudad values(1084, 'VILLAMARIA', 17);
insert into ciudad values(1085, 'VILLANUEVA', 13);
insert into ciudad values(1086, 'VILLANUEVA', 85);
insert into ciudad values(1087, 'VILLANUEVA', 44);
insert into ciudad values(1088, 'VILLANUEVA', 68);
insert into ciudad values(1089, 'VILLAPINZON', 25);
insert into ciudad values(1090, 'VILLARRICA', 73);
insert into ciudad values(1091, 'VILLAVICENCIO', 50);
insert into ciudad values(1092, 'VILLAVIEJA', 41);
insert into ciudad values(1093, 'VILLETA', 25);
insert into ciudad values(1094, 'VIOTA', 25);
insert into ciudad values(1095, 'VIRACACHA', 15);
insert into ciudad values(1096, 'VISTA HERMOSA', 50);
insert into ciudad values(1097, 'VITERBO', 17);
insert into ciudad values(1098, 'YACOPI', 25);
insert into ciudad values(1099, 'YACUANQUER', 52);
insert into ciudad values(1100, 'YAGUARA', 41);
insert into ciudad values(1101, 'YALI', 5);
insert into ciudad values(1102, 'YARUMAL', 5);
insert into ciudad values(1103, 'YAVARATE', 97);
insert into ciudad values(1104, 'YOLOMBO', 5);
insert into ciudad values(1105, 'YONDO', 5);
insert into ciudad values(1106, 'YOPAL', 85);
insert into ciudad values(1107, 'YOTOCO', 76);
insert into ciudad values(1108, 'YUMBO', 76);
insert into ciudad values(1109, 'ZAMBRANO', 13);
insert into ciudad values(1110, 'ZAPATOCA', 68);
insert into ciudad values(1111, 'ZAPAYAN', 47);
insert into ciudad values(1112, 'ZARAGOZA', 5);
insert into ciudad values(1113, 'ZARZAL', 76);
insert into ciudad values(1114, 'ZETAQUIRA', 15);
insert into ciudad values(1115, 'ZIPACON', 25);
insert into ciudad values(1116, 'ZIPAQUIRA', 25);
insert into ciudad values(1117, 'ZONA BANANERA', 47);
insert into ciudad values(1118, 'SUCRE', 19);